Repository jwt-dotnet/jwt, pull requests merged in 2018-03, with the labels that each got.

#161 Promoting NuGet package to 4.0.0 Release
  src/JWT/JWT.csproj
Labels: core

#160 Support multiple keys for decoding
  src/JWT/Builder/ClaimName.cs
  src/JWT/Builder/JwtBuilder.cs
  src/JWT/IJwtDecoder.cs
  src/JWT/IJwtValidator.cs
  src/JWT/JWT.csproj
  src/JWT/JwtDecoder.cs
  src/JWT/JwtValidator.cs
  tests/JWT.Tests.Common/JwtBuilderDecodeTest.cs
  tests/JWT.Tests.Common/JwtBuilderEncodeTest.cs
  tests/JWT.Tests.Common/JwtDecoderTest.cs
  tests/JWT.Tests.Common/JwtSecurityTest.cs
  tests/JWT.Tests.Common/Models/TestData.cs
Labels: enchantment

#163 Update README.md
  README.md
Labels: bug, enchantment
