Repository jwt-dotnet/jwt, pull requests merged in 2021-04, with the labels that each got.

#324 Used correct algorithm HMACSHA384 in HMACSHA384Algorithm class
  src/JWT/Algorithms/HMACSHA384Algorithm.cs
  src/JWT/JWT.csproj
Labels: bug

#325 Memory optimization in JwtEncoder.Encode method
  src/JWT/JWT.csproj
  src/JWT/JwtEncoder.cs
Labels: enchantment

#315 Added support for .NET 5
  .pipelines/build.yml
  JWT.sln
  src/JWT/Algorithms/ECDSAAlgorithm.cs
  src/JWT/Algorithms/ECDSAAlgorithmFactory.cs
  src/JWT/JWT.csproj
  src/JWT/JwtValidator.cs
  src/JWT/Properties/AssemblyInfo.cs
  tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmFactoryTests.cs
  tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmTests.cs
  tests/JWT.Tests.Net50/JWT.Tests.Net50.csproj
  tests/JWT.Tests.NetCore2/JWT.Tests.NetCore2.csproj
  tests/JWT.Tests.NetCore3/JWT.Tests.NetCore3.csproj
  tests/JWT.Tests.NetCore3/JwtBuilderEndToEndTests.cs
Labels: core, up-for-grabs
