Repository jwt-dotnet/jwt, pull requests merged in 2022-06, with the labels that each got.

#399 Added null-checks to JwtDecoder.Validate()
  src/JWT/Algorithms/NoneAlgorithm.cs
  src/JWT/JwtDecoder.cs
Labels: enchantment

#405 Added null-check for keys in ValidSymmetricAlgorithm()
  src/JWT/JwtDecoder.cs
Labels: enchantment

#409 Fixed JwtBuilder.Encode() with custom factory
  src/JWT/Builder/JwtBuilder.cs
  src/JWT/JWT.csproj
  tests/JWT.Tests.Common/Builder/JwtBuilderEncodeTests.cs
Labels: bug

#411 PackageLicense to PackageLicenseExpression
  src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
  src/JWT.Extensions.DependencyInjection/JWT.Extensions.DependencyInjection.csproj
  src/JWT/JWT.csproj
Labels: enchantment

#414 Fixing typos in exception messages
  src/JWT/Builder/JwtBuilder.cs
Labels: enchantment, bug

#416 Fixed tests, build on Arch Linux
  tests/JWT.Tests.Common/Algorithms/RSAlgorithmFactoryTests.cs
  tests/JWT.Tests.Common/Algorithms/RSAlgorithmTests.cs
Labels: bug, build

#415 Added Encode<T>(T payload) so we have symmetry with Decode<T>(string token)
  src/JWT/Builder/JwtBuilder.cs
  src/JWT/JWT.csproj
  src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs
  tests/JWT.Tests.Common/Builder/JwtBuilderEncodeTests.cs
  tests/JWT.Tests.Common/Models/TestData.cs
Labels: core

#417 Added a Table of Contents on the README.md
  .pipelines/build.yml
  README.md
Labels: enchantment, documentation
